---
swagger: "2.0"
info:
  description: "Contrato Módulo de Votación - API Newport App"
  version: "1.0.7"
  title: "API Newport APP"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "Votation"
schemes:
- "https"
- "http"
paths:
  /votacion/obtener:
    post:
      tags:
      - "Votation"
      summary: "get home page to votation section"
      description: ""
      operationId: "getVotation"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RequestVotationHome"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Votation"
  /votacion/obtener-grupos:
    post:
      tags:
      - "Votation"
      summary: "get alternatives per group"
      description: ""
      operationId: "getVotationAlternatives"
      consumes:
        - "multipart/form-data"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RequestGetAlternatives"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/VotationGroups"
  /votacion/registrar-votos:
    post:
      tags:
      - "Votation"
      summary: "register votes"
      description: ""
      operationId: "postRegisterVote"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RequestVotationRegisterAlternative"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/VotationRegisterAlternative"
definitions:
  Votation:
    type: "object"
    properties:
      listaVotacionConfiguracion:
        type: "array"
        items:
          properties:
            id:
              type: "integer"
            nombreEvento:
              type: "string"
            nombreAplicacion:
              type: "string"
            inicioPeriodo:
              type: "string"
              format: "date-time"
            finPeriodo:
              type: "string"
              format: "date-time"
            sitioId:
              type: "integer"
            tipoCliente:
              type: "string"
              enum:
              - "CATEGORIA"
              - "TODOS"
            frecuenciaVotacionId:
              type: "integer"
            cantidadVotosInfinity:
              type: "integer"
            cantidadVotosGalaxy:
              type: "integer"
            cantidadVotosSky:
              type: "integer"
            cantidadVotosUniverse:
              type: "integer"
            cantidadVotosStar:
              type: "integer"
            cantidadVotosSinClubCard:
              type: "integer"
            isPopupPrincipal:
              type: "boolean"
            fondoPopupInicial:
              type: "string"
            fondoPortadaVotacion:
              type: "string"
            fondoPortadaVotacionFin:
              type: "string"
            fondoPopupFinalVotacion:
              type: "string"
            fondoPopupYaParticipaste:
              type: "string"
            fondoInicioSorteo:
              type: "string"
            fondoInteraccionSorteo:
              type: "string"
            fondoInicioResultado:
              type: "string"
            fondoResultado:
              type: "string"
            estado:
              type: "boolean"
            tipoVotacion:
              type: "object"
              properties:
                id:
                  type: "integer"
                nombre:
                  type:
                    "string"
                maximoGrupos:
                  type:
                    "integer"
                estado:
                  type:
                    "boolean"
                nombreConstante:
                  type: "string"
                  enum:
                  - "VERSUS"
                  - "MULTIPLE"
                  - "VALORACION"
            puedeInteractuar:
              type: "boolean"
      tarjetaClienteCategoria:
        type: "string"
    xml:
      name: "Votation"
  VotationGroups:
    type: "object"
    properties:
      listaGruposAlternativas:
        type: "array"
        items: 
          type: "object"
          properties:
            id:
              type: "integer"
            titulo:
              type: "string"
            orden:
              type: "integer"
            estado:
              type: "boolean"
            votacionConfiguracionId:
              type: "integer"
            alternativas:
              type: "array"
              items:
                properties:
                  id:
                    type: "integer"
                  nombre:
                    type: "string"
                  orden:
                    type: "integer"
                  foto:
                    type: "string"
                    default: "image name. (Is null if votation type is Valoracion)"
                  votacionGrupoId:
                    type: "integer"
    xml:
      name: "VotationGroup"
  VotationRegisterAlternative:
    type: "object"
    properties:
      registroCorrecto:
        type: "boolean"
    xml:
      name: "VotationRegisterAlternative"
  RequestVotationRegisterAlternative:
    type: "object"
    properties:
      votacionId:
        type: "integer"
      listaAlternativas:
        type: "array"
        items:
          type: "integer"
    xml:
      name: "RequestVotationRegisterAlternative"
  RequestVotationHome:
    type: "object"
    properties:
      sitioId:
        type: "integer"
    xml:
      name: "RequestVotationHome"
  RequestGetAlternatives:
    type: "object"
    properties:
      votacionId:
        type: "integer"
    xml:
      name: "RequestGetAlternatives"
